LOVDnl/LOVD3

src/changelog.txt, src/class/template.php, src/diseases.php, src/genes.php, src/individuals.php, src/screenings.php, src/transcripts.php, src/users.php, src/variants.php, src/view.php
dropdown menus of the tabs
- The view all diseases associated with gene option was missing in the
diseases tab.
=> - The view page titles are made consistent with the menu options in the

src/changelog.txt, src/class/object_columns.php, src/class/object_diseases.php, src/class/object_users.php, src/class/objects.php, src/class/template.php, src/diseases.php, src/users.php
This PR fixes issue on Trello card: "A curator's VE has nice list of genes that expands. Let's build the same for the shared column's VE (diseases or genes). Use code from curator's VE."
It also concerns setting mysql concat_group_max_len setting in a new query run before viewEntry or loadEntry.
Note before merging: links generated for the custom columns point to the genes/diseases for now. They can be changed to point to the custom column data for that specific gene/disease. Let me know if that's needed.
=> Trello tasks 0402

git_hooks/create_hook_symlinks.sh, git_hooks/pre-commit
pre-commit is run just before a commit is made. The script checks all added/modified php files for their headers. Currently it checks for the existence of the modification date (current date) copyright year (current year) and author (name/email from the git config). If one of the checks fails the commit is aborted.
The pre-commit hook requires python 3.  Install the hook by running create_hook_symlinks.sh which will create a symlink in .git/hooks
@ifokkema, please see if it's useful for you, currently it checks for your name/email in the file header based on the git config -- which is different from what's in the file header in your case I believe. If you're not going to use it, we may as well keep it out of source control.
=> Added a git pre-commit hook for checking *.php file headers.

src/class/object_logs.php, src/genes.php, src/inc-init.php
Now logs:
* Changes to edit privileges
* Shown/hidden curators
* Order of curators
Resolves #25
=> Improved logging for management of curators for genes.

.travis.yml, src/changelog.txt, src/diseases.php, src/genes.php, tests/bash_scripts/convert_selenium_to_phpunit.sh, tests/selenium_tests/admin_tests/delete_gene_IVD, tests/selenium_tests/admin_tests/delete_gene_IVD.php, tests/selenium_tests/manager_tests/delete_gene_GJB, tests/selenium_tests/manager_tests/delete_gene_GJB.php
@ifokkema  Please check whether warning messages are clear and informative.
Resolves #29
=> Added double warning before deleting gene or disease.

src/inc-init.php
Updated URLs from trac to github for reporting issues.
Resolves #42
=> Updated links to LOVD issue reporter (github).

src/users.php
=> Added links to unfinished submissions for managers in user's page.

src/class/object_genome_variants.php, src/class/object_individuals.php, src/class/object_phenotypes.php, src/class/object_screenings.php
=> Allow userID=0 while editing/importing objects.

tests/selenium_tests/admin_tests/delete_gene_IVD.php, tests/selenium_tests/collaborator_tests/add_summary_variant_located_within_gene.php, tests/selenium_tests/collaborator_tests/add_summary_variant_only_described_on_genomic_level.php, tests/selenium_tests/collaborator_tests/add_summary_variant_seatlleseq_file.php, tests/selenium_tests/collaborator_tests/add_summary_variant_vcf_file.php, tests/selenium_tests/manager_tests/delete_gene_GJB.php, tests/selenium_tests/submitter_tests/add_summary_variant_located_within_gene.php, tests/selenium_tests/submitter_tests/add_summary_variant_only_described_on_genomic_level.php, tests/selenium_tests/submitter_tests/add_summary_variant_seatlleseq_file.php, tests/selenium_tests/submitter_tests/add_summary_variant_vcf_file.php
Fixed failing tests after the most recent commit introduced textual changes.
=> Fixed failing tests

src/changelog.txt, src/class/object_transcripts.php, src/inc-init.php, src/inc-upgrade.php, src/install/inc-sql-tables.php, src/transcripts.php
=> Added remarks field for transcripts.

src/changelog.txt, src/import.php
Fixes #67 
@ifokkema: Let me know if this solves #67 to your satisfaction, see the discussion in the issue's comments.
=> Let import check the import file first for panels (of individuals).

src/inc-auth.php, src/inc-init.php, tests/selenium_tests/manager_tests/test_block_submitter_registration.php, tests/selenium_tests/manager_tests/test_read_only_state.php
Also fixes "Headers already sent" warnings from PHP Unit.
=> Attempt to fix broken branches for chrome tests

src/inc-upgrade.php, src/install/inc-sql-tables.php
=> Removed default values for TEXT fields.

tests/selenium_tests/LOVDSeleniumBaseTestCase.php, tests/selenium_tests/admin_tests/create_user_manager.php, tests/selenium_tests/authorization_tests/create_user_collaborator.php, tests/selenium_tests/authorization_tests/create_user_owner.php, tests/selenium_tests/collaborator_tests/create_user_collaborator.php, tests/selenium_tests/manager_tests/create_user_submitter.php, tests/selenium_tests/phpunit_bootstrap.php, tests/selenium_tests/shared_tests/create_user_manager.php, tests/selenium_tests/shared_tests/create_user_submitter.php, tests/selenium_tests/submitter_tests/create_user_submitter.php
* Also adapted tests that create user accounts to use unCheck() for
setting mail option.
=> Automatic retry setting checkbox in BaseTestCase class.

src/changelog.txt, src/class/objects.php, src/download.php
They are now allowed 5 minutes of processing time.
=> Large downloads are now allowed to take a longer time, to make sure they finish before the server interrupts them.

src/inc-lib-init.php
- Allows for genomic and transcriptomic variants to be parsed.
- Is not a full HGVS checker, because it doesn't verify things like substitutions not having ranges.
- Can process 3' UTR variants as well, as long as an existing transcript is given (internal ID or NCBI ID).
- Returns false on some failure, otherwise returns an array with 2 or 4 positions and the variant type.
- Needed for #58.
=> Added lovd_getVariantInfo() function.

src/changelog.txt, src/genes.php
Fixes issue that is ocurring on shared installation for XKRX gene.
Fixes #200
=> Fix gene edit page for issue #200

src/changelog.txt, src/variants.php, src/view.php
=> Better error text when no transcripts with underlying variants are found

src/inc-lib-form.php
Simplify query to check DBID for mysql 5.7.5+ default full group by setting.
Fixes #185
=> Simplify query to check DBID

src/changelog.txt, src/class/object_genome_variants.php, src/class/object_transcript_variants.php, src/scripts/refseq_parser.php
=> Changed links to HGVS nomenclature to current website.

src/class/object_genes.php
=> Rename links to exon/intron tables on gene homepage.

src/2Do.txt, src/changelog.txt, src/class/object_users.php
=> Show number of owned phenotypes in user viewEntry.

src/changelog.txt, src/class/object_diseases.php, src/inc-init.php, src/inc-upgrade.php, src/install/inc-sql-sources.php
* Added 'hpo_disease' as an external source.
* Use OMIM ID to link to HPO.
Fixes #107
=> Added link to HPO from disease viewEntry.

src/changelog.txt, src/class/objects.php, src/screenings.php
=> Show variants on screening page based on number of variants linked. 

src/class/objects.php
=> Simplify message when no results while searching on cols without display info

src/2Do.txt, src/class/object_custom_viewlists.php, src/class/objects.php, src/inc-init.php
- Implemented VL speedups from LOVD+.
- Applied other small fix from LOVD+.
- Cleaned up 2Do.txt a bit and committed forgotten change to modified date.
- Moved "Effect unknown" variant effect to the bottom of the selection list.
- This should make users less likely to select it, and more likely to let them fill in an actual value.
=> Some speedups and other minor changes.

src/class/objects.php, src/diseases.php, src/inc-js-viewlist.php, src/individuals.php, src/phenotypes.php, src/screenings.php, src/styles.css, src/users.php, src/variants.php, src/view.php
Note: currently only activated in the unique variants view.
Fixes #202
=> Filter viewlists based on multiple values for a column

src/changelog.txt, src/genes.php, src/inc-init.php, src/transcripts.php
- Implemented LOVD_Objects::turnOffMappingDone() where it was forgotten.
- Added forgotten changelog entries, and forgotten issue numbers.
- Version bump to 3.0-20.
=> Release 3.0-20

src/ajax/viewlist.php, src/class/objects.php, src/columns.php, src/diseases.php, src/genes.php, src/individuals.php, src/links.php, src/logs.php, src/phenotypes.php, src/references.php, src/screenings.php, src/scripts/convert_lovd2.php, src/submit.php, src/transcripts.php, src/users.php, src/variants.php, src/view.php
All parameters in an "option array".
=> Viewlist function refactoring

src/scripts/convert_lovd2.php
=> Fix interference between transcripts VLs with same VL ID.

src/genes.php
=> View gene homepage by HGNC ID.

src/users.php
Updated the ORCID API from v.1.2 to v.2.1.
- API version 1.2 was discontinued.
- LOVD will now read the employer info, if present.
- LOVD now supports reading multiple email addresses.
=> Updated the ORCID API from v.1.2 to v.2.1.

src/changelog.txt, src/inc-init.php, src/inc-upgrade.php
Release 3.0-21.
- Added changelog entries for all changes.
- Version bump to 3.0-21.
=> Release 3.0-21.

src/class/objects.php
Allow LOVD3 to nicely display JSON data in fields.
- VLs just show "(data)" and don't display the data.
- VEs show a table structure displaying the JSON data. May not work for all data, but works for most.
- Implemented for the VKGL data that is now in the shared GV LOVD3.
=> Allow LOVD3 to nicely display JSON data in fields.

src/scripts/readingFrameChecker.php
Updated the ReadingFrameChecker; it now provides the correct (new) HGVS nomenclature.
- The old notation (c.154-?_295+?del) was not correct anymore.
- The new notation is c.(153+1_154-1)_(295+1_296-1)del.
=> Updated the ReadingFrameChecker; it now provides the correct (new) HGVS nomenclature.

src/references.php
Fixed some problems with the DOI view.
- Pagination was off, but especially if you're searching by journal you need pagination.
- Fixed the journal search; DOIs can also contain slashes and journal names can contain dots.
- Cleaned up the code a bit.
=> Fixed some problems with the DOI view.

src/scripts/convert_lovd2.php
Updated the LOVD2 to LOVD3 converter.
- Updated the reference handling.
- Can now also handle DOIs.
- Added support for `{PMID:PubMed 2019 abstract:12345678}` format. The script will fetch the paper's author and year using eutils and rewrite the reference to `{PMID:Author et al (Year):12345678}`.
- Implemented a cache to make sure eutils doesn't get the same question twice.
- Updated `lovd_callJSONService()` to be able to return an array instead of an object.
- Updated column mappings and handling.
- Added mappings for `Patient/Age_death`, `Patient/Age_onset` and `Patient/Age_diagnosis`.
- Updated value conversion for gender, geographic origin, screening technique, screening template and genetic origin.
- Added support for converting phenotype OMIM IDs to LOVD3 Diseases, and support for …
=> Updated the LOVD2 to LOVD3 converter.

src/class/api.submissions.php
Some Submission API improvements:
- Fixed a minor data formatting bug in HPO terms and added some automated data formatting for RNA and protein fields.
- HPO terms should not be stored as "HP:123456 (term)" but instead as "term (HP:123456)".
- If RNA has not been checked, the RNA description will automatically get parentheses if they are absent.
- If RNA has not been checked, the protein description will automatically get parentheses if they are absent.
- The default protein change is now only "-" for non-coding transcripts. For coding transcripts, it's now "p.(?)".
- If a gene is given for a variant, and it exists in LOVD, it must match with the given transcript.
=> Submission API improvements

src/api.php
The JSON variant API didn't select for a gene correctly.
Correct implementation of #408.
=> The JSON variant API didn't select for a gene correctly.

src/class/api.submissions.php
Added support for `VariantOnGenome/ClinicalClassification` and `VariantOnGenome/ClinicalClassification/Method` in the submission API.
- The method will be filled in if we find something that equals one of the methods in the pathogenicity comments. There is currently no VarioML field for it.
=> Added support for clinical classification columns.

src/users.php
Fixed the registration spam filter.
- Adapted for new StopForumSpam API output format.
- Don't reject registrations just because of their username.
Closes #428.
=> Fixed the registration spam filter.

src/changelog.txt, src/inc-init.php
=> Released 3.0-24.

doc/tex/manual.tex, src/class/objects.php, src/inc-js-viewlist.php, src/inc-lib-viewlist.php
Added a "how to query" information dialog to VLs that have pagination on.
- Renamed the JS function `lovd_showLegend()` to `lovd_showDialog()`, making it more generic.
- Added a dialog to VLs that have pagination about how to query the VL.
- Added new examples to the manual and some small fixes to the examples.
=> Added "how to query" information dialog.

src/__function_list.txt, src/changelog.txt, src/import.php, src/inc-init.php
Release 3.0-26.
- Added changelog for 3.0-26.
- Version bump to 3.0-26.
- Also fixed some indentation in import.php.
- Added note to function list; we still have lots of 5.3 users even though I'd like to go up to 5.4.0.
=> Release 3.0-26.

src/genes.php
When creating a gene by its symbol, recheck if we don't already have it.
When creating a gene by its HGNC ID, LOVD checks if we already have that HGNC ID in the database. LOVD didn't do that if you use the symbol, it only checked if we have that symbol already. So for genes who've changed symbol, it was possible to open the create gene form using its new symbol, after which you would get a query error. Now, LOVD checks if we have the HGNC ID already once we fetched that from the HGNC.
Closes #515.
=> When creating a gene by its symbol, recheck if we don't already have it.

src/__function_list.txt, src/changelog.txt, src/class/template.php, src/docs/index.php, src/inc-init.php, tests/selenium_tests/shared_tests/create_summary_data_upload_vcf.php
Release 3.0-27.
- Small changes that haven't been committed yet.
- Update docs info page.
- Version bump to 3.0-27.
- Updated changelog.
=> Release 3.0-27

src/inc-init.php, src/install/inc-sql-tables.php
=> Define Genome_builds table

src/class/object_genome_builds.php, src/class/object_genome_variants.php
Added a percentage bar to the VE give an idea of the completion of the genome build.
Related to #550
=> Percentage complete

src/INSTALL.txt, src/ajax/import_scheduler.php, src/class/PDO.php, src/class/graphs.php, src/class/object_columns.php, src/class/object_individuals.php, src/class/object_system_settings.php, src/class/objects.php, src/class/template.php, src/diseases.php, src/inc-init.php, src/scripts/refseq_parser.php, src/submit.php
Synced LOVD+ improvements and fixes to LOVD3.
- Fix notices, disable some code for LOVD+, and minor improvements.
- Change the last references to `document.location` to the better `window.location`.
- Some small textual fixes and updates.
- Fix errors in coding styles and old `implode()` syntax.
=> Sync changes from LOVD+.

src/class/api.ga4gh.php
I forgot part of the implementation, and we need it this weekend.
=> Fix date implementation in the GA4GH API.

src/api.php, src/class/feeds.php
- Fix warnings generated by newer versions of PHP.
- Also allow HGNC IDs to be used in the LOVD2-style API. This is especially useful if LOVD stores an older gene symbol.
- Add the gene's HGNC ID also to the gene's JSON output.
- Prevent issues with variants containing double semicolons.
- Add all relevant VOT data (DNA, RNA, protein) to the JSON output.
- This required a new element to not break existing implementations that were reading out the `Variant/DNA` field. To keep all data together per transcript, built a new array that groups the data. E.g.,
```json
[
{
"symbol": "ARSD",
"id": "0000186422",
"position_mRNA": [
"NM_001669.3:c.1000+855",
"XM_005274514.1:c.1000+855",
"XM_005274515.1:c.1000+855",
"XM_005274516.1:c.1073"
],
"position_genomic": {
"hg19": "chrX:2832742"
}, …
```
=> Several improvements to the LOVD2-style API.

src/changelog.txt, src/docs/index.php, src/inc-init.php
- Update the LOVD3 manual information on the docs page.
- Version bump to 3.0-30.
- Add the changelog for 3.0-30.
=> Release 3.0-30

src/inc-init.php, src/inc-lib-form.php
- Set up the email headers as an array, fixing issues with `PHP_EOL`.
- Adapt `lovd_sendMail()` to handle the headers in array format.
=> Fix email issues
