- src/ajax/get_gene_switcher.php
- src/changelog.txt
- src/class/template.php
- src/styles.css
Reviewed r709:
- Saved bandwidth and increase efficiency, by selecting and downloading only the data that's necessary for the autocomplete.
- Coding style fixes.
- For selection list: auto select current gene, like LOVD3 did before.
- Auto submit autocomplete list on selecting the gene from the list.
- Placed back old comments and code that had been removed.
- The autocomplete field gets focus on initialization.
- Use jQuery rather than old-style JS.
- Moved width specification of autocomplete field to the field itself. Not the styles.css, which sets it for all future autocomplete fields.
- Reverted styles.css to previous state.
- Improved changelog entries, and white space changes by editor.
> Review r709

- src/class/object_custom_viewlists.php
- src/class/object_diseases.php
- src/class/object_genes.php
- src/class/object_genome_variants.php
- src/class/object_individuals.php
- src/class/object_phenotypes.php
- src/class/object_screenings.php
- src/class/object_transcripts.php
- src/class/objects.php
All numeric fields in viewlists are right-aligned. Table headings in viewlists are not affected anymore by custom html attributes.
> Viewlist alignment

- src/changelog.txt
- src/class/object_transcripts.php
Transcript viewlists on pages transcript/geneID and genes/geneID now
shows a variant count depending on the user level. Specifically, a user
with a level lower than collaborator will see the count for variants
with status public, plus variants that are either owned or created by
him.
> Variant count in transcript viewlist takes status and ownership into account.

- src/changelog.txt
- src/class/object_system_settings.php
- src/class/object_users.php
- src/inc-lib-form.php
- tests/open_close_form.php
Improvements to getForm() form generator in inc-lib-form.php. Blocking the autofill browser feature for password fields is off by default. All password fields are preceded by a hidden text field to avoid mistakenly autofilling the username in some unrelated text field.
Resolves #27
> Prevent browsers from auto-filling usernames in data entry forms

- src/inc-js-variants.php
All css classes were being deleted in javascript for input field VariantOnGenome/DNA. This broke the error reporting. I removed the deletion, as it didn't seem to have purpose (the function doesn't set a class attribute for the field anywhere else).
Closes #39
> Removed css class deletion for form field VariantOnGenome/DNA

- src/changelog.txt
- src/inc-lib-variants.php
- Notices where thrown in the script that called Mutalyzer's NameChecker. With notices turned on, this resulted in the never finishing of the loading.
- With notices turned off, it resulted in an empty protein change, while this field is mandatory.
- LOVD will now default to r.(?)/- for non-coding transcripts.
- Later we'll have to implement r.(=) for intronic variants on non-coding transcripts.
- Also fixed bug that splicing errors returned a wrong RNA description:
- Fixed bug; RNA prediction of a variant affecting splicing was 'r.(?)' instead of 'r.spl?'.
> Protein prediction failed for non-coding transcripts.

- src/changelog.txt
- src/inc-lib-form.php
- Variants with both a chromosomal DBID and a gene's DBID, were assigned new gene-specific DBIDs, instead of reusing the existing one.
- When many observations of the variant existed, LOVD kept assigning new DBIDs and the number of different values per unique variant would increase with every new observation.
- Waiting for travis test to complete. Upon absence of failures, will be merged into master.
> Fixed problem with double DBID assignment.

- src/class/object_users.php
- src/inc-js-submit-userform.php
- src/login.php
- src/users.php
The IP allow list feature needed clarification.
- Clarified that the IP address list is optional.
- Clarified that the IP address list field's default value is *.
- Added JS notice with a warning when user sets the IP address allow list.
- When the form warns about the field being filled in, and you press "Cancel", the IP address list field receives focus.
- Added the IP addresses to the email sent to the user after registering.
- Added a message to the email body when the IP address list has been set to something other than '*'.
- When user is blocked by IP, the manager info is shown.  …
- This, so that the user can know who to contact to get help.
- Clarified we don't support IPv6 for restricting access:  …
* The form won't show your current address any more, when it's IPv6.
* When it's …
> Clarify IP allow list feature

- src/changelog.txt
- src/import.php
Fixed bug in the update import:
- Fixed bug; When updating data using the update through import beta feature and leaving the owned_by field out of the file or empty, LOVD would overwrite the existing value with the ID of the user importing the file.
- Currently, no default value will be filled in for the owned_by field when updating, also not when the file is given in the file but left empty.
- This is now consistent with the statusid column, that had been modified previously to no longer apply defaults for updates through import.
- Closes #66.
> Fixed bug in the update import

- src/changelog.txt
- src/import.php
Fixed update import bug:
- Fixed bug; When running the update import, LOVD would complain if fields are not filled in correctly, even if those fields are not defined in the file.
- Now, if updating, LOVD will ignore errors that are linked to fields that are not in the file that is being imported.
- Closes #53: "Importing records fails on existing fields in database".
> Fixed update import bug

- src/ajax/viewlist.php
- src/changelog.txt
- src/class/object_users.php
- src/users.php
- tests/selenium_tests/access_sharing_tests/access_sharing_submitter.php
Fixed bug; Submitters could find a way to access the full users list.
- Submitters have access to the Users object for access sharing.
- This access was partially granted in 3.0-16, but the actual security issue was introduced later when the VL was released to submitters, so they could search and sort the access sharing VL.
- Certain columns were hidden for security reasons by the access sharing page, but manipulating the VL directly allowed any submitter to get a full list of the LOVD users with full columns.
- The columns hidden in the access sharing page are now forced to be hidden in any users VL for submitter level users.
- Additionally, hid the username field, and unhid the ID field.
- Fixed typo in changelog.txt.
> Fixed bug; Submitters could find a way to access the full users list.

- src/changelog.txt
- src/class/object_diseases.php
- The list of genes selectable to be linked to the disease were built up from two lists, and array_unique() was used to not have duplicates.
- However, without running array_values(), keys may be missing from the list. This can result in query errors.
> Fixed bug; For curators, editing a disease could result in a query error.

- src/inc-lib-init.php
Too much whitespace was added to the SOAP login information, breaking the headers. Part of the headers then got attached to the POST information.
> Fixed bug; The recent SOAP fix broke POST calls over proxy servers using the fsockopen() implementation.

- src/changelog.txt
- src/genes.php
- src/inc-lib-genes.php
Databases set to strict mode would refuse to create such genes.
> Fixed issue with HGNC returning multiple OMIM IDs sometimes.

- src/class/object_custom_viewlists.php
Fixes issue where some viewlists had no rowlink for certain rows.
Closes #134.
> Set fallback to vogid as row_id in custom viewlists with VOG/VOT tables.

- src/changelog.txt
- src/columns.php
- src/references.php
Could have removed some of the `inc-lib-columns.php` inclusions, but now their presence can remind us we may need to split that file, and keep the inclusion for the functions that stay in it.
Fixes #136.
> Custom columns could no longer be edited because of a double inclusion of a library file.

- src/changelog.txt
- src/users.php
None of the links actually worked because of security measures, now the menu has been removed.
> Fixed bug; Curators were given an actions menu when viewing other users.

- src/changelog.txt
- src/variants.php
In 3.0-17, the `id` column was renamed in many VLs. In one VL, this caused a problem because PHP and JS code was still referring to it with `search_id` which should have been `search_tid` instead.
> Fixed bug; The "Manage transcripts for this variant" feature didn't allow the removal of a transcript anymore due to an error introduced in 3.0-17.

- src/changelog.txt
- src/import.php
Every table was considered a linking table, making all columns mandatory, even `edited*` columns.
> Fixed bug; Importing data failed for installations with a '2' in the table prefix, because the import code misunderstood the table types that way.

- src/class/template.php
- When announcements were present, the sticky header would "float" away from the top of the page when scrolling.
- Now, the announcements are grouped in a DIV together with the header, to have them float together on the top of the page.
- The new offset for the table with the menu is now calculated based on assumptions of the announcement height in the HTML, but then calculated by JS directly after rendering the header tables, after which the margin is corrected if needed by the actual measurements.
> Fixed problem with sticky header when announcements are present.

- src/changelog.txt
- src/class/object_users.php
- src/login.php
- Fixed bug; When a user needed to change the password, the force option didn't work properly, and could be circumvented.
- Improved data form when changing the password after unlocking your account, to clarify that you need to insert the unlocking code again for confirmation.
> Fixes when changing your password.

- src/__function_list.txt
- src/ajax/auth_token.php
- src/ajax/viewentry.php
- src/changelog.txt
- src/class/object_users.php
- src/inc-init.php
- src/inc-lib-init.php
- src/inc-upgrade.php
- src/install/inc-sql-tables.php
- src/users.php
Users can now create their own API tokens to use for the future LOVD data submission API.
- Adapted data model to store authorization token and its expiration date.			
- Added fields to users VE; the token (hidden, only link shown for more info) and the token expiration.
- Needed `lovd_convertSecondsToTime()` from LOVD+ for the latter.
- Clicking the link for the API token information opens a dialog that's fed through an AJAX request.
- Dialog shows some information on the token, also displays buttons to create and revoke the token.
- Dialog displays when token has expired, and asks for confirmation when creating a new one while one is still valid.
- Dialog can create a new token, setting the expiration.
- Dialog can revoke a token.
- Both features are CSRF protected.
- Modernized …
> Let users configure an API token

- src/changelog.txt
- src/class/object_genome_variants.php
- src/class/object_users.php
- src/import.php
- src/inc-init.php
- src/inc-upgrade.php
- When an Administrator creates a new user, the new default level is Submitter.
- Fixed issues with the variant effect fields:
- The variant effect columns were checked twice while submitting and importing, possibly resulting in repeated error messages.
- Fixed bug; The variant effect fields didn't have a default value when importing.
- Fixed issues with the position fields:
- Fixed bug; Imports could set variant start positions that were higher than variant end positions.
- When variants are imported without position fields or variant type filled in, LOVD will now predict them.
- Fixed bug; Variants that were imported with empty intron positions, didn't group together with variants that had a 0 filled in.
- All variants already imported that way, are fixed.
- Closes #140.
> Minor fixes

- src/changelog.txt
- src/class/object_custom_viewlists.php
- src/variants.php
Fix problem with manage transcripts feature.
- Fixed bug; Transcripts could not easily be added to variants anymore.
- This was caused by the recent changes making LOVD compatible with the new default `ONLY_FULL_GROUP_BY` MySQL setting.
- Closes #167: "Manage transcripts feature doesn't allow addition of transcript anymore".
- Fixed bug; The filter for transcripts to add didn't work anymore if you had removed all transcripts from the list.
- The filter got disabled when all transcripts were removed, because the lovd_AJAX_viewListSubmit() disables empty filters.
- Also fixed forgotten copyright header in class/object_custom_viewlists.php.
> Fix manage transcripts feature

- src/changelog.txt
- src/class/object_custom_viewlists.php
Fixed bug; The "all variants affecting transcripts" view showed only one entry.
- This error is related to #167.
- This was caused by the recent changes making LOVD compatible with the new default `ONLY_FULL_GROUP_BY` MySQL setting.
- There was no more GROUP BY defined, after which MySQL grouped all results into one.
- Closes #176: "Viewlist entry count differs from what is displayed".
- Checked all other Custom VLs for this error as well, now they are all fine.
> Fix "all variants affecting transcripts" VL

- src/changelog.txt
- src/class/PDO.php
- src/genes.php
- src/install/index.php
- src/transcripts.php
Fixed "Invalid default value for 'start_date'" error during LOVD installation.
- This occurs on newer MySQL versions that have STRICT_MODE enabled by default as well as NO_ZERO_DATE, which disallows a zero date and returns a fatal error.
- This fix works by removing the NO_ZERO_DATE SQL mode for the session that LOVD runs in.
- Closes #143.
- Closes #173.
Fixed "Field 'tissues' doesn't have a default value" error during LOVD installation.
- This occurs on newer MySQL versions that have STRICT_MODE enabled by default, which disallows NOT NULL TEXT columns not mentioned during an insert.
- This fix works by adding the fields to the insert query, putting in empty strings.
- Closes #143.
> Fix MySQL errors during installation on newer MySQL versions

- src/changelog.txt
- src/class/graphs.php
Fixed bug; Graph variantsTypeProtein() returned a query error after application of fix for SQL mode "ONLY_FULL_GROUP_BY".
- It didn't like the "FUNCTION(MIN(column)) AS alias GROUP BY alias" structure.
- Also removed the MIN() from a "MIN(column) GROUP BY column" structure in variantsTypeDNA(). It didn't cause an error, but didn't have any effect, either.
> Fixed query errors in gene graphs page.

- src/install/index.php
- tests/selenium_tests/shared_tests/create_gene_GJB.php
- tests/travis/setup/setup_apache.sh
Overwrite default signature for development and test installations based on `$_SERVER['SERVER_ADMIN']`. Fixes #174 
@ifokkema: I was not able to test on the receiving end whether the correct signature was set. Do you know how to do this? As of now there should be test installations showing up in the statistics with the following signatures (name -- md5 hash):
travis_CI_3.0 -- 1951dc9caea4b8c053d26612d1d7eee2
mkroon_local_3.0 -- f85e532c2b3819323effc9d3be4baa02
> Let dev/test installations identify themselves correctly

- src/changelog.txt
- src/scripts/refseq_parser.php
- The "Include link to GenBank record" field in the final step sometimes contained more text than just an GenBank record ID.
- The regexp somehow expected text after the ID, now we no longer do.
> Minor bug fix in the refseq parser.

- src/changelog.txt
- src/class/objects.php
- src/inc-js-viewlist.php
Let users open a link from a row in a viewlist by clicking with the middle button of the mouse. Pure javascript row links are unaffected.
Fixes #196.
> Let viewlist rows open link in new window with middle-click.

- src/class/object_individuals.php
Fixed bug with editing individuals with large numbers of diseases.
- Due to LOVD not fetching all diseases for the form, not all diseases were loaded into the form, and as such it was not in one go possible to remove all diseases, and not possible at all to remove certain diseases without removing others.
- Fixes #192.
> Fixed bug with editing individuals with large numbers of diseases.

- src/class/objects.php
Fixed accasional deadlocks in the loading of ViewLists.
- The explicitly set isolation level of "serializable" could cause deadlocks. Removed the isolation level setting.
- This has been tested in the LOVD3 shared database for two months today, and stopped deadlocks from happening (which were 1-2 per month).
- Fixes #233.
> Fixed accasional deadlocks in the loading of ViewLists.

- src/class/object_custom_viewlists.php
This fixes odd behavior of MySQL where the row_id somtimes contains zerofilled-numbers and sometimes not. (e.g. depending on presence of `ORDER BY` clause.)
Chosen solution was to cast the parts of the row_id explicitly. 2 options here, either cast the id and then take the aggregate of multiple rows with `MIN()`, or the other way around.
Performance of possible solutions compared to original (average of 10x generating the variant list for the MECP2 gene (nearly 120.000 entries)):
Master 3.0-18 20170619: 2.136
MIN(CAST()):            2.168
CAST(MIN()):            2.151
In the end, `CAST(MIN())` was chosen as the most performant solution, although the differences are small.
Fixes #205
> Explicitly cast parts of viewlist row_id to integer.

- src/changelog.txt
- src/class/object_genes.php
- src/variants.php
Fix ugly link to reading frame checker when there are no variants.
- Fixes #237.
- Also, empty OMIM IDs were no longer sent to MySQL as NULL.
> Fix ugly link to reading frame checker when there are no variants.

- doc/tex/manual.tex
Add the URL of the new public list of LOVDs on the LOVD3 site, instead of using the 2.0 website URL.
Don't see the need to regenerate the manual, for just the URL change. The old URL remains to work anyway.
Closes #246.
> Add the URL of the new public list of LOVDs on the LOVD3 site, instead of using the 2.0 website URL.

- src/ajax/map_variants.php
- src/changelog.txt
- src/class/object_diseases.php
Fixing small things.
- Fixed bug; The variant mapper gets stuck when encountering variants with their position set to 0.
- When manually mapping a variant, only handle the flagging of the variant if there actually are positions known.
- Moved the display of the HPO column on the Diseases VE next to the OMIM field instead of after the edited* fields.
> Fixing small things

- src/changelog.txt
- src/class/object_individuals.php
- src/class/object_screenings.php
- src/class/object_users.php
* Links to overviews are similar to those for data owned by the given
user.
* Edited individual and screening classes to include created_by in
their viewlist (hidden but searchable).
Fixes #190
> Added links to overviews of created entries on user page.

- src/changelog.txt
- src/class/object_individuals.php
New legend text for panel size. Decided on following text for form:
> Number of individuals this entry represents; e.g. 1 for an individual, 5 for a family with 5 affected members. To report different Individuals from one family link them using the field "ID of panel this entry belongs to".
And for viewlist:
> Number of individuals this entry represents; e.g. 1 for an individual, 5 for a family with 5 affected members.
Fixes #191
> Clearer description of panel_size field for individuals.

- src/changelog.txt
- src/class/object_genome_variants.php
Do not allow `effect_reported` to be set to "not classified" when statusid is "Public".
Fixes #213
> Fix effect_reported not set by curator

- src/class/template.php
The content area in HTML is now repositioned using javascript based on
the actual height of the sticky header. The predicted height may be
wrong even when there are zero announcements. (e.g. when the standard
logo is replaced with a larger image like in issue #277).
Fixes #277
> Reposition content area based on header size even when no announcements.

- src/changelog.txt
- src/import.php
- tests/selenium_tests/import_tests/false_insert_import.php
* Fix #245 by making sure that a phenotype object set during parsing of
a previous line is removed when field `diseaseid` is empty, in order
to avoid that the wrong phenotype object is used in later processing
of the current input line.
Fixes #245
> Remove lingering phenotype objects set during import.

- src/changelog.txt
- src/inc-lib-users.php
This is a minor fix; it's just type casting the value before it's sent to MySQL.
Fixes #283.
> Fixed bug; Colleagues couldn't be assigned with MySQL's default strict mode.

- src/ajax/map_variants.php
- src/changelog.txt
- src/import.php
- src/variants.php
Fixed the variant position calculation:
- Replaced all calls to Mutalyzer's mappingInfo that were not also mapping requests by calls to the lovd_getVariantInfo() function.
- Fixed bug; When automatically mapping variants of genes on the antisense strand, the variant positions were stored in the wrong order.
Closes #58.
> Fixed the variant position calculation

- tests/travis/setup/setup_chrome.sh
- tests/travis/setup/setup_selenium_server.sh
Temporary changes to get correct versions of browser and driver that are able to work together. Look at the Fixmes to undo these changes and resume to the latest versions of both the browser and the driver.
> Revert Travis build to use older version of Chrome and chromedriver.

- src/changelog.txt
- src/inc-js-viewlist.php
- src/phenotypes.php
* Let javascript handler of search args in URL hash ignore hidden search fields.
* Do not set search argument for page `/phenotypes/disease` in GET array directly, but in URL of redirect.
* Fixes #292
> Fix issue with search params when using browser back button.

- src/class/objects.php
* Use the field name directly for ordering if it occurs as an alias.
* Otherwise use specified database field name as before.
* Fixes #291.
> Use field alias for ordering in viewlists if possible.

- src/changelog.txt
- src/inc-init.php
Fixed possible backslashes in LOVD's path introduced by Windows.
- Amongst other places, lovd_getProjectFile() is affected by this, and this can cause various issues like being unable to import data.
> Fix windows paths

- src/ajax/auth_token.php
- src/api.php
- src/class/api.submissions.php
- src/class/objects.php
- src/inc-init.php
- src/reset_password.php
Fix submission API issues.
- Display the admin's email address better when it's multiple addresses.
- Added LSDB ID to Admin's Auth Token dialog.
- This way the Admin can find out which ID the clients need to use to start submitting data into the LOVD.
- Fixed bug; 3'UTR variants were not accepted.
- lovd_getVariantInfo() should be run passing the transcript ID in such cases.
- Fixed query errors coming from LOVD_Object::getRowCountForViewList().
- This function tries to calculate the row count for each VL query, without having to use MySQL's SQL_CALC_FOUND_ROWS().
- It takes the VL query and simplifies it as much as possible, removing unused selects, joins and sorts, and then getting the COUNT(*).
- Searches cause query errors in this function where newlines are placed in the query …
> Fix submission API issues

- src/scripts/convert_lovd2.php
Somehow Chrome and Firefox handle CSS setting `white-space: nowrap` differently, causing an issue in Firefox in the LOVD2 conversion script, showing no newlines in the output. Setting `white-space: pre` fixes this, and it's the suitable setting for this use.
> Fix issue non-display of newlines in lovd2 conversion script output.

- src/2Do.txt
- src/class/object_custom_viewlists.php
- src/class/object_genome_variants.php
- src/class/object_individuals.php
- src/class/object_phenotypes.php
- src/class/object_screenings.php
- src/class/objects.php
Fixed bug; The color coding was visible for the public.
- Color coding based on the variant's status should not be shown to the public, also because they don't see the status column.
- Made sure the color coding was done only for users >= LEVEL_COLLABORATOR.
- Also made sure the color coding logic was in one place only, instead of copied in many different files.
- Color coding is based on the lowest set status (unique variant view and view with variant and patient data in one row).
> Fixed bug; The color coding was visible for the public.

- src/class/objects.php
Removed requirement that the viewlist query returned field 'owned_by' as well as 'owned_by' and the 'owner' array. All relevant info is available in the 'owner' field.
Fixes #307
> Fix issue where owner tooltip did not show in some VLs.

- src/ajax/viewlist.php
Fixed security bug and fixed broken external viewer.
- aColsToSkip was now trusted to be set in SESSION, but we did not check if it actually was set in SESSION. The recent removal of code that enforced the removal of certain columns for lower level users, allowed these users to forge an AJAX request that would show the links anyway. Reinstated this code. Luckily, this change had not been released, it was done after the 3.0-20a release.
- aColsToSkip was needed for the external viewer. Not being able to set it anymore, resulted in lots of additional columns for the country node views.
> Fixed security bug and fixed broken external viewer.

- doc/tex/manual.tex
- src/class/object_custom_viewlists.php
- src/class/object_genome_variants.php
- src/class/object_transcript_variants.php
Change field descriptions for variant effect:
Affects function (reported) -> Affects function (by submitter)
Affects function (concluded) -> Affects function (by curator)
Also changed legends for the corresponding fields to a suitable description.
> New names for variant effect by submitter/curator.

- src/class/api.submissions.php
- src/class/object_custom_viewlists.php
- src/import.php
- src/inc-js-viewlist.php
- src/inc-lib-init.php
Interface related fixes:
- Fixed bug; In the grouped views, data owners were not shown when the department field was empty.
- Fixed bug; The in_gene view didn't group by transcript, but merely by gene and vot.id.
- This resulted in unpredictable sorting and the not showing of transcripts that did have variants.
- Which transcript was shown appeared to be random for the user, and wasn't clear.
- Now, all VOT entries will be shown.
- Fixed bug; The back button didn't clear the MVS filter, which rendered the view broken when selecting a column without conflicting values.
- This happened as $bSearch is false at the moment, and thus no VL header is shown.
Submission API related fixes:
- When not sending the cleaned JSON to the archive JSON file, we might not be able to create a file at all.
- …
> Various fixes

- src/class/object_genome_variants.php
- src/variants.php
Fixed bug; Submitters could submit data without a variant effect by disabling all transcripts of the gene they selected.
- Now, we take into account which transcripts have been disabled when we check if transcripts are being used.
> Fixed bug; Submitters could submit data without a variant effect by disabling all transcripts of the gene they selected.

- doc/tex/manual.tex
- src/api.php
- src/class/feeds.php
- src/inc-init.php
Make the LOVD2-style API return JSON on request.
- Sending the `format=application/json` variable in the `GET` query string will make the API return JSON.
- Also, added created and edited dates for variants to the API.
- Variant API now returns created_by and owned_by fields.
- JSON will return these as arrays.
- Atom will return these as authors and contributors.
- Explode variant effects for JSON output.
- When requesting an entry by its ID, the JSON data will not return an array of entries, but just one entry.
- This is more in line with how the Atom API was returning an Atom entry instead of a feed.
- JSON sends the curators of a gene also in an array.
- JSON dates are also ISO 8601 format.
- Updated the Atom's Feed class a bit to not always convert dates anymore and simplified some …
> Make the LOVD2-style API return JSON on request

- src/scripts/refseq_parser.php
Updated the RefSeq Parser to only show transcripts of the gene passed to it.
- Long lists of genes like on the Shared LOVD3 instance could crash or freeze the user's browser.
- Closes #314.
> Updated the RefSeq Parser to only show transcripts of the gene passed to it.

- .travis.yml
- src/__function_list.txt
- src/ajax/viewlist.php
- src/inc-init.php
- src/install/index.php
Various small fixes.
- Added the external viewer's LOVD-wide full data view.
- Rights must be added in the ajax/viewlist file.
- Removed remnants of mentions of the XML library that we used to use.
- Prevent bounces by removing Mark's email address, as it's not active anymore.
- Fixed bug; Curators would lose non-public individuals on their gene's Individuals listing when sorting or searching the listing.
- The authorization wasn't loaded in the ajax script that shows the data.
> Various small fixes.

- src/class/object_custom.php
- src/class/object_custom_viewlists.php
Fixed bug; Incomplete custom links could break the unique variant view's HTML.
- Now being more strict on matching the custom links. Incomplete ones should simply not be recognized anymore.
> Fixed bug; Incomplete custom links could break the unique variant view's HTML.

- src/class/api.submissions.php
Some improvements were needed to the submission API to support more data that our users are currently already submitting.
- Added support for sending dbSNP IDs in the submission API.
- Adding support for literature links for the submission API.
- db_xref pubmed links can now be passed.
- If only the ID is given, the author name and publication year is retrieved from pubmed.
- If only the name is given, it's treated as normal text.
- If both are given, the ID is used for the link and the name as the label.
- Added mapping from non-standard "literature" element data to the PubMed link.
- Prevent notices during writing to file, when columns were added later in the file.
- Added support for `genetic_origin` for the submission API.
- Genetic origin, its source and evidence codes (the latter …
> Submission API improvements.

- src/class/object_genome_variants.php
- src/class/object_individuals.php
- src/class/template.php
- src/diseases.php
- src/docs/index.php
Fixed some speed issues.
- Don't run the DBID checks like `lovd_checkDBID()` anymore, when running an update import that doesn't even touch the DBID.
- Even just updating variant effects in a big file took forever.
- Speed up the Individuals VL on the Diseases VE.
- It was doing a `HAVING` on the concatted Disease IDs. This is slow in large JOINs.
- Created an optional, additional JOIN that is only used for searching on the Disease ID without limiting the list of Diseases shown.
- On the shared, this decreases the query time from 6 seconds to 0 seconds.
- Copyright date bump to 2019.
- Updated docs stats.
> Fixed some speed issues.

- src/class/object_users.php
- src/inc-init.php
- src/inc-upgrade.php
- src/install/inc-sql-tables.php
Fix username field to also allow for email address.
- Enlarged the username field to 50 characters.
- When the username field is not smaller than 50 characters, it will not be touched.
- Allow also an email address as a username.
- Version bump to 3.0-21c.
> Fix username field to also allow for email address.

- src/class/object_custom.php
Fixed bug in find & replace; selection lists were not exploded and compared per option value, but compared by the whole column's value.
- Exploding would only be done when importing; now also activated it for running F&R.
- Also, the list of valid options will now be shown, when there is a mismatch.
> Fixed bug in find & replace; selection lists were not exploded and compared per option value, but compared by the whole column's value.

- src/inc-lib-init.php
- tests/unit_tests/GetVariantInfoTest.php
Fixed bug; `lovd_getVariantInfo()` didn't recognize delins variants.
- Also updated tests.
> Fixed bug; lovd_getVariantInfo() didn't recognize delins variants.

- src/ajax/map_variants.php
- src/class/objects.php
- src/download.php
- src/genes.php
- src/inc-js-viewlist.php
- src/inc-lib-users.php
- src/transcripts.php
Multiple bug fixes.
- Fixed bug; The mapper didn't fill in the VOT's effectid, but left it at its default.
- Now, it'll take the VOG's effectid and it'll copy it.
- The public gene-specific downloads had some non-public columns included, like status, created_by, created_date, etc.
- These are now removed. They're not damaging to be shared, but they're not shown on VLs or VEs, so they should remain hidden in the download as well.
- A download will now no longer show inactive Phenotype and VOT columns, if filters are active for Diseases or Genes, respectively.
- This cleans up the file a lot for single-gene downloads.
- It reports a warning for Phenotype data, since it's possible that data is selected unrelated to the selected Disease(s).
- When creating a transcript without selecting a …
> Multiple bug fixes.

- src/references.php
- Allow for journal-specific queries using the DOI reference search.
- Normally DOI reference searches are on the full DOI only (like 10.1002/humu.21438). Now, also allow for searches using the journal's DOI, like 10.1002/humu.
- Also allow for searching for DOIs of a certain publisher, like 10.1002.
Closes #257.
> Allow for publisher and journal-specific queries using the DOI reference search.

- src/class/PDO.php
- src/class/object_custom_viewlists.php
Fix `variants/in_gene` view.
- Disable SQL mode `ONLY_FULL_GROUP_BY`; it is causing problems.
- Even if we try to play nice, the totally unnecessary MIN() and MAX() calls slow down queries a lot.
- Removed unneeded `MIN()` and `MAX()` calls from custom viewlists.
- When VOT is joined to Transcripts, use `INNER JOIN`, and no longer group on Transcript columns.
- This speeds up the query quite a lot.
- Also, rename `LEFT JOIN`s to `LEFT OUTER JOIN`s to make more clear what they are.
Closes #386.
> Fix `variants/in_gene` view.

- src/api.php
- src/class/graphs.php
- src/class/object_custom_viewlists.php
- src/class/object_genes.php
- src/columns.php
- src/screenings.php
- src/submit.php
Reverted most `ONLY_FULL_GROUP_BY` changes. Respecting this SQL mode that was on by default since a recent MySQL version, added lots of `MIN()` and `MAX()` function calls to the queries. This slowed down many queries, and the changes were sometimes done without checking if the query could perhaps be written differently.
Other changes:
- For BED files, always return the mapping on the earliest transcript.
- For the genes list, assume the gene is in sense when at least one transcript is in sense.
- Also simplified SELECTs whereever possible for custom ViewLists.
- Custom VLs with VOG as the first table (Variant VL on Screenings VE and Individual VE) no longer show the minimal VOT's effectid, but instead the VOG's effectid, which makes much more sense.
- Genes are assumed to be in sense when …
> Reverted ONLY_FULL_GROUP_BY changes.

- src/ajax/viewlist.php
- src/individuals.php
- src/screenings.php
Several fixes in the security of ViewLists.
- Fixed security issue in loading the authorization for ViewLists.
- During Find & Replace implementation, the code was changed to load the gene-specific authorization using `$_REQUEST` rather than `$_GET`. However, the filtering of the results was still using `$_GET`. Hence, authorizations can be loaded forging a `$_POST` request while not necessarily filtering the results using `$_GET`.
- This allowed Curators to craft special requests to load VLs with non-public data of other genes.
- Solved this by enforcing filtering when authorizing Curators.
- Made it a bit harder for ViewLists to get their ColsToSkip overridden.
- Hiding columns for a VL is stored in session upon defining the VL. However, VLs can be loaded independently of being defined …
> Several fixes in the security of ViewLists.

- src/class/PDO.php
- src/class/api.php
- src/class/api.submissions.php
- src/class/feeds.php
- src/class/graphs.php
- src/class/object_announcements.php
- src/class/object_basic.php
- src/class/object_columns.php
- src/class/object_custom.php
- src/class/object_custom_viewlists.php
- src/class/object_diseases.php
- src/class/object_genes.php
- src/class/object_genome_variants.php
- src/class/object_individuals.php
- src/class/object_links.php
- src/class/object_logs.php
- src/class/object_phenotypes.php
- src/class/object_screenings.php
- src/class/object_shared_columns.php
- src/class/object_system_settings.php
- src/class/object_transcript_variants.php
- src/class/object_transcripts.php
- src/class/object_users.php
- src/class/objects.php
- src/class/pedigree.php
- src/class/progress_bar.php
- src/class/template.php
Some fixes to the objects.
- Hide the reference field from the user data entry form.
- Don't hard-code what are shared objects in the object definitions themselves, keep it in one place.
- Fix class definitions to match the coding standards.
> Some fixes to the objects.

- src/inc-init.php
- src/variants.php
Added LOVD+ feature to delete all of a variant's mapping to transcripts that are not labeled as "preferred".
- This is mainly to reduce the diff between LOVD and LOVD+, the feature is not active for LOVD.
- An `ACTION` can now contain a hyphen.
> Added LOVD+ feature to delete all of a variant's mapping to transcripts not labeled as "preferred".

- src/class/template.php
- src/inc-init.php
- src/inc-upgrade.php
The `$_SERVER['REQUEST_URI']` variable needed additional protection.
- XSS risk in combination with gene switcher.
- XSS risk in combination with updater.
- Simplified sanitizing `$_PE` in inc-init.php.
> The $_SERVER['REQUEST_URI'] needed additional protection.

- src/class/object_custom_viewlists.php
- src/class/template.php
Fixed row links from Individuals and Screenings VEs to VOG VE.
- The transcript ID is not available for the VOG VLs, so this sent a zData string into the URL. Then the VOG VE didn't open any VOTs, even when present.
- Rowlink for VOG/VOT VLs now depends on the order in which the objects are loaded.
Also:
- Updated copyright notice to 2020.
> Fix VOG row link.

- src/class/api.submissions.php
- src/class/object_individuals.php
Make adding a disease or phenotype mandatory.
- Make entering a Disease mandatory from the data entry forms.
- Make submitting phenotype data mandatory when using the submission API.
- The submitters that I know from the GV shared that are using this API, all submit phenotype data already.
> Make adding a disease or phenotype mandatory.

- src/ajax/import_scheduler.php
- src/ajax/viewentry.php
- src/ajax/viewlist.php
- src/class/object_individuals.php
- src/class/template.php
- src/download.php
- src/inc-init.php
- src/inc-lib-form.php
- src/inc-lib-init.php
- src/inc-upgrade.php
- src/install/inc-sql-tables.php
- src/install/index.php
Sync LOVD+ features.
- LOVD+ additional files now have the PLUS suffix instead of the MOD suffix.
- Added code of LOVD+ feature to import files as second screenings. This code is not active in LOVD.
- Added function for conditional SQL for the upgrade script, and the feature to show version-specific messages during upgrade.
- Added feature that speeds up generating multiple DBIDs in one page load (for instance, during import).
- This mostly helps when an index has been placed on the DBID column, which is not on by default.
- LOVD will now place an index on the DBID column while installing and during upgrade to 3.0-24.
- Added the `column_exists_has_no_key` option to `lovd_addConditionalSQL()` for this.
- Added options to `user_level_settings` setting in `$_SETT`, and applied in …
> Sync LOVD+ features.

- src/ajax/curate_set.php
- src/class/object_individuals.php
- src/class/object_logs.php
- src/class/objects.php
- src/individuals.php
- src/phenotypes.php
- src/variants.php
Quick curation and Curate submission features.
- Added the "Curate (publish) selected entries" option in the Options menu of several VLs.
- Opens a dialog which shows the entries that need to be curated, and the curation results.
- Public entries are checked as well, and any possible errors are displayed.
- Non-public entries are published when no errors have occurred.
- Gene timestamps are updated when entries are published.
- Added "Publish (curate) entire submission" feature to the Individuals' VE Options menu.
Also:
- Cleaned up a badly named variable, which caused a lot of unnecessary code.
- Adapted `objects.php` to get mandatory multiple selection fields checked properly. Empty arrays were not regarded as empty fields since normally the browser doesn't send these arrays.
- Fixed …
> WIP: Quick curation and Curate submission features.

- src/api.php
The JSON variant API didn't select for a transcript, but also not for a gene; it was returning all variants in the database.
- Made sure we select for either a transcript or a gene.
> The JSON variant API didn't select for a transcript, but also not for a gene.

- src/api.php
Fixed API sorting.
- Adapted API; now listing transcripts in gene entries sorted on the number of variants they contain.
- Now using the transcript with the most variants for the variants API as well.
- Also, collect only unique VOT mappings, without repeated data.
- Rebuilt the BED file API; sort VOTs to use based on the transcript with the most variants.
- Sorting wasn't as easy as sorting the transcripts for the gene list for some reason.
- Simplified the code flow as well by merging the two parts related to the BED files.
- Fixated all sorting by also sorting on t.id, so transcripts with an equal number of variants don't randomly sort.
This all enables a much higher number of variants returned from the APIs.
> Fixed API sorting.

- src/class/object_custom_viewlists.php
- src/class/object_links.php
- src/import.php
- src/inc-lib-viewlist.php
- src/individuals.php
- src/phenotypes.php
- src/scripts/refseq_parser.php
- src/variants.php
- src/view.php
Fixed notices and deprecated function calls.
- Fixed notices that occurred when searching for just a '!' in a text field.
- Fixed notices when non-public Individuals or Phenotypes were edited by submitters.
- This was already fixed in `variants.php` in a slightly different way, but apparently I overlooked checking other files back then.
- Removed deprecated `each()` calls from `variants.php` and `view.php`, and sorted given transcripts on NCBI ID.
- Removed deprecated `each()` calls from `import.php`, `object_links.php`, and `scripts/readingFrameChecker.php`.
- Fixed notices in unique variant view when viewers bypassed the `cols_to_skip` by loading the VL directly over ajax.
> Fixed notices and deprecated function calls.

- src/class/api.submissions.php
Improved handling of OMIM IDs and HPO terms in submission API.
- When individuals are submitted with HPOs but without OMIM IDs, the `unclassified/mixed` `diseaseid` will now also be linked to the individual.
- This feature is hereby removed for submissions with multiple OMIM IDs. And instead of assigning the HPO terms to the `unclassified/mixed` disease, they will be assigned to the first OMIM ID sent by the submitter.
- This makes sure the submission will be directly acceptable for curation, since having a `diseaseid` is now mandatory.
> Improved handling of OMIM IDs and HPO terms in submission API.

- src/inc-js-columns.php
- tests/selenium_tests/shared_tests/create_custom_column_phenotype.php
When creating or editing a custom column, the example width bar didn't change anymore when you set the column's width.
- JQuery now needs `val()` instead of `attr('value')` to get and set the input's value.
- Added a test for this feature.
> Fixed column's example width bar.

- src/class/api.submissions.php
- src/class/object_custom_viewlists.php
- src/class/object_genome_variants.php
- src/class/object_transcript_variants.php
- src/inc-init.php
- src/inc-upgrade.php
- tests/selenium_tests/submitter_tests/add_variant_only_described_on_genomic_level_to_CMT_individual.php
Removed additional variant effect values, that have been added in #261.
- Removed variant effects made redundant by the new `VOG/ClinicalClassification` column from the variant effect definitions in `inc-init.php`.
- Removed the redundant variant effect values from the effect table using the upgrade script.
- Updated the variant effect legends, which unfortunately are stored in three places.
- Fixed test that broke after removal of the special effect IDs.
> Removed additional variant effect values.

- src/variants.php
- src/view.php
When viewing a gene's variants, choose which transcript to display based on the VOT count, not the NCBI ID.
- Fixed the same sorting bug in the full gene's view.
- The VOT count is used to sort API results as well since #410, so this makes the GUI consistent with the API.
- Closes #420.
> Fix transcript sorting in gene-specific views.

- src/class/variant_validator.php
- src/scripts/fix_variant_descriptions.php
Improved the Variant Validator scripts. Our validation script is now working through chromosome 8. Implementing what we've learned so far.
- Improved handling processing errors.
- If there are transcripts that work, remove the ones that don't. Otherwise, if we have selected transcripts, retry without doing so.
- When a processing error occurs because we failed to handle it, throw a warning (`WFLAG`) instead of an error (`EFLAG`).
- Variants keep randomly failing; increase tries but implement an incremental sleep as well.
- Ignoring methylation variants, as they can't be processed anyway.
- Skip variants that have already been checked and marked with an error.
- Accept existing `p.(=)` variant descriptions for intronic dups even when VV thinks a `p.?` is more suitable.
- Fixed bug; Panics …
> Improved the Variant Validator scripts.

- src/scripts/fix_variant_descriptions.php
Fixed the Variant Validation script.
- Fixed bug; Instead of skipping variants with logged errors, it was skipping variants without logged errors.
- Ignore WGAP warnings when the predicted cDNA change is actually WT.
- Updated `panic()` code a bit; because of using `array_merge_recursive()` to merge `$aVV` and `$aVVVOT`, we may have ended up with arrays.
> Fixed the Variant Validation script.

- doc/tex/manual.tex
- src/class/object_genes.php
- src/inc-upgrade.php
- src/install/inc-sql-links.php
- tests/selenium_tests/shared_tests/check_custom_links.php
Fixed several custom link issues.
- Replaced hardcoded PubMed link on the gene homepage to use the databases's PubMed link, for the processing and on the gene information data entry form.
- Enabled the DOI custom link for the gene's Reference field.
Also:
- Updated the PubMed link to the new format in `install/inc-sql-links.php` and `inc-upgrade.php`.
- Updated the PubMed link to the new format in the tests.
- Updated the manual to use the new PubMed link format for our own links to PubMed.
Closes #430.
> Fixed several custom link issues.

- src/login.php
- src/reset_password.php
Improved the "forgot my password" feature.
- Added the "forgot my password" link to the login form also before trying to log in.
- Clarified on the reset password form that an email will only be sent when we find a matching account.
- Also, users are reminded to check if this is the LOVD installation that they're registered to.
- Allow resetting an account's password as well with the account's email address.
- If the email address is used by multiple accounts, using the username is still required.
- Accounts, where the email address is the only address, are preferred over accounts where the address is one of the addresses.
- Removed useless code, probably present from the LOVD2 to LOVD3 code migration.
Closes #432.
> Improved the "forgot my password" feature.

- .travis.yml
- src/download.php
- src/individuals.php
- tests/selenium_tests/admin_tests/verify_full_download.php
- tests/selenium_tests/shared_tests/create_gene_IVD.php
- tests/test_data_files/AdminTestSuiteResult.txt
Added feature to download a submission.
- Added download format for a single submission.
- Added link to the new download format from the Individual VE, for data owners only.
Also:
- Added the user's ID to the file name when downloading all of your own or somebody else's data.
- Fixed bug; User-specific downloads didn't include the Diseases that Phenotype entries were linked to, only Diseases that Individuals were linked to.
- Added a FIXME for speeding up downloads and making them less memory intensive.
- I think it's quite a lot of work and I don't have time for this at the moment, so I've documented what is necessary and we'll do it later.
- Fixed download test, LOVD's version from the download template mismatched the current version.
- Added more waiting time to the gene creation …
> Added feature to download a submission.

- src/class/variant_validator.php
- src/inc-lib-init.php
- src/inc-lib-variants.php
- src/scripts/fix_variant_descriptions.php
Improved the Variant Validation script.
- Increased the sleep on a failure with a factor two, which should reduce the number of failures.
- Added code that handles `WFLAG` warnings because of processing errors.
- There's nothing we can do, continue so at least we'll have a hg38 mapping (hopefully).
- Fixed broken display of hg38 DNA prediction when panicking.
- Improved comparing transcript predictions when checking WGAP warnings.
- Don't take LOVD's first transcript but take the first transcript both the LOVD record and the VV prediction have in common.
- Overwrite protein values also when LOVD record has `p.(fs*)` but we have something better.
- Overwrite LOVD's hg38 value if all it contains is `g.?`.
- Overwrite protein values also when LOVD record has `p.fsX` but we have something …
> Improved the Variant Validation script.

- src/class/object_genes.php
Fixed link to Ensembl by removing the name we added to it.
- The Ensembl genome browser ignores the BED track's name, and just puts "bed". The previous method we used to configure the name doesn't work anymore, it breaks the loading of the track. The documentation does not mention how to name your track, and anything that I've tried failed.
Closes #438.
> Fixed link to Ensembl by removing the name we added to it.

- src/class/api.php
- src/inc-init.php
Fixed the link to the NCBI sequence viewer.
- It was doing a HEAD request to the BED file API before doing a GET, which wasn't supported by our API.
- Added support for HEAD requests to the LOVD2-style API, the NCBI sequence viewer loads the BED file OK.
Closes #439.
> Fixed the link to the NCBI sequence viewer.

- src/columns.php
- src/inc-js-variants.php
- src/variants.php
- tests/selenium_tests/LOVDSeleniumBaseTestCase.php
- tests/selenium_tests/shared_tests/create_submission_individual_with_IVA.php
- tests/selenium_tests/shared_tests/create_summary_variant_located_within_gene_with_multiple_transcripts.php
- tests/selenium_tests/shared_tests/manage_transcripts_for_variant.php
Fixed mapping to genome feature, which wasn't working if the genomic DNA field was emptied.
- This was caused by jQuery no longer supporting `attr('value')` calls, but wanting `val()` calls instead.
- Replaced all `attr('value')` calls throughout LOVD with `val()` calls.
Closes #444.
- jQuery now uses `val()` to set fields instead of `attr("value")`, which means we can't use xpath anymore to wait for certain values.
- Added `waitForValueContains()` convenience function to wait until a certain element's value contains the given string.
- Replaced `waitForElement()` calls with xpaths based on the value with the new `waitForValueContains()` convenience function.
> Fixed mapping to genome feature.

- src/scripts/convert_lovd2.php
Added support for the LOVD2 Variant/DbSNP column.
- Mapping it to `VariantOnGenome/DbSNP`.
- Converting the LOVD2 values.
Closes #437.
> Added support for the LOVD2 Variant/DbSNP column.

- src/reset_password.php
Improved the "forgot your password" feature:
- When resetting your password using an email address, mention the account's username in the log entry so we can still find these resets.
- Updated password reset email body, clarifying the text and adding the current username to the output.
- Closes #448.
> Improved the "forgot your password" feature.

- src/ajax/merge_entries.php
- src/class/object_logs.php
- src/class/objects.php
- src/individuals.php
- src/screenings.php
Added feature to merge entries (Individuals and Screenings, for now).
- Enabled the merge entries option for the Individuals VL and the Screenings VL on the Individual's VE.
- The script collects the selected IDs from the given VL, prepares an array with instructions, verifies with the user, and executes the merge.
- In case of conflicts, the merge is not processed and the conflicts are listed.
- Possible post action options are loading another page, reloading the current page, reloading a VL, or unchecking all checkboxes.
- After a merge of Individuals, uncheck all checkboxes, reload the VL, and redirect to the merged entry.
- After a merge of Screenings, uncheck all checkboxes and reload the VL.
- For Screenings, safely merge differences in Template and Technique.
- For Individuals, the …
> Added feature to merge entries.

- src/announcements.php
- src/changelog.txt
- src/class/api.submissions.php
- src/columns.php
- src/configuration.php
- src/diseases.php
- src/docs/index.php
- src/download.php
- src/genes.php
- src/import.php
- src/inc-lib-init.php
- src/individuals.php
- src/links.php
- src/logs.php
- src/phenotypes.php
- src/references.php
- src/screenings.php
- src/settings.php
- src/submit.php
- src/transcripts.php
- src/users.php
- src/variants.php
Small fixes.
- Fixed bug; Replacement of "A, B, C" to "A, B and C" was done badly.
- The replacement wasn't done because of an error in the regexp, but also the grammar was bad. The result should be "A, B, and C".
- Replaced non-breaking spaces everywhere in the source code with normal spaces.
- Allow for `lovd_getVariantInfo()` to recognize WT calls.
- When passing a badly configured transcript to `lovd_getVariantInfo()`, don't always die.
- We might not even need the positions from the database. Die only when we do.
- This allows using badly configured transcripts for variants in the 5' UTR and the CDS.
> Small fixes.

- src/scripts/convert_lovd2.php
Fixed two issues in LOVD2 converter.
- Added support for multiple diseases per individual for the LOVD2 converter, if separated by a semicolon (`;`).
- Fixed type in VOG/dbSNP field.
Closes #454.
> Fixed issues in LOVD2 converter.

- src/inc-lib-form.php
Fixed the lovd_fetchDBID() function. It was, under some circumstances, generating DBIDs that are already in use.
- Fixed bug; The optimization to check for existing DBIDs only in the same gene causes problems when relevant variants are no longer connected to the gene in question.
- The speedup is now done on the chromosome field.
- Optimize the DBID gene selection; it was always switching genes when going through the options.
- Now it only does that when the numeric ID is lower.
- Some more optimizations in `lovd_fetchDBID()`.
Close #460.
> Fixed lovd_fetchDBID() function.

- src/ajax/api_settings.php
- src/ajax/auth_token.php
- src/class/api.php
- src/class/api.submissions.php
- src/class/object_users.php
- src/class/objects.php
- src/import.php
- src/inc-init.php
- src/inc-upgrade.php
- src/install/inc-sql-tables.php
- tests/selenium_tests/admin_tests/verify_full_download.php
- tests/selenium_tests/shared_tests/submission_API.php
- Added the `api_settings` column to the users table.
- Version bump to 3.0-24b.
- Display the API settings on the user account's detailed view and added a link in the Users VE to edit the API settings.
- Added new ajax script to store API settings for users.
- These are dynamic settings, and we can add or change settings without having to alter the user table anymore.
- Added setting for allowing variant-only submissions.
- Added setting for auto-scheduling submissions.
- Also, updated the return message of the API to make this difference clear, but only for API v2.
- Updated test for this.
- Added setting for directly publishing new API submissions.
Closes #462.
- Added additional pathogenicity values, mapping to already existing effects and classifications.
- This is just to extend …
> Improved the submission API to allow direct processing of variant-only submissions.

- src/ajax/mobidetails.php
- src/class/api.submissions.php
- src/class/template.php
- src/inc-init.php
- src/inc-js-openwindow.php
- src/inc-lib-init.php
- src/inc-lib-viewlist.php
- tests/selenium_tests/LOVDSeleniumBaseTestCase.php
- tests/selenium_tests/manager_tests/block_submitter_registration.php
- tests/selenium_tests/manager_tests/create_announcement_making_LOVD_readonly.php
- tests/selenium_tests/manager_tests/delete_announcement.php
- tests/selenium_tests/shared_tests/access_submission_from_colleague.php
- tests/selenium_tests/shared_tests/add_more_data_to_existing_submission.php
- tests/selenium_tests/shared_tests/assign_colleague_to_owner.php
- tests/selenium_tests/shared_tests/assign_curator_to_IVD_not_authorized.php
- tests/selenium_tests/shared_tests/create_custom_column_phenotype.php
- tests/selenium_tests/shared_tests/create_submission_individual_with_IVA.php
- tests/selenium_tests/shared_tests/create_summary_data_upload_seattleseq.php
- tests/selenium_tests/shared_tests/create_summary_data_upload_vcf.php
- tests/selenium_tests/shared_tests/create_summary_variant_located_within_gene_with_multiple_transcripts.php
- tests/selenium_tests/shared_tests/curate_submission_step_by_step.php
- tests/selenium_tests/shared_tests/delete_disease_IVA.php
- tests/selenium_tests/shared_tests/delete_disease_IVA_not_authorized.php
- tests/selenium_tests/shared_tests/delete_gene_IVD.php
- tests/selenium_tests/shared_tests/enable_custom_column_for_IVA.php
- tests/selenium_tests/shared_tests/enable_custom_column_for_individuals.php
- tests/selenium_tests/shared_tests/install_LOVD.php
- tests/selenium_tests/shared_tests/login_as_submitter.php
- tests/selenium_tests/shared_tests/manage_transcripts_for_variant.php
Small improvements to how LOVD handles the link to MobiDetails.
- Don't offer to submit a variant to MD when there is no API key configured.
- Updated `lovd_openWindow()` - it now accepts "_blank" as a window name, in which case it'll open up a new window (browser tab).
- Updated MD ajax script - open MD in a new browser tab instead of a popup.
- Added a bit more info on MobiDetails to its dialog window.
Tests are regularly randomly failing because the test instance is too slow. Assertions that check for URLs then fail because that URL hasn't been reached yet. Replaced all assertions for an URL that depend on time, with a wait function that waits for the URL to match.
- Added `waitForURLContains()` for partial matching.
- Added `waitForURLEndsWith()` for suffix matching.
- Added …
> Fixed many small issues.

- src/class/variant_validator.php
Fixed problems with `verifyVariant()`.
- Let `verifyVariant()` deduce the genome build from the NC, when passed.
- Updated VV's `verifyVariant()` - strip off the NC when it's unnecessary.
- Sending the NC may cause problems when there is a sequence difference between the NC and the NM. So send the NC only when necessary. See https://github.com/openvar/variantValidator/issues/218.
- The NC is necessary for intronic variants or for variants outside of the boundaries of the transcript.
Closes #469.
> Fixed verifyVariant().

- src/ajax/mobidetails.php
- src/variants.php
Improved the link to MobiDetails.
- Now that MobiDetails supports sending hg19 variants, better always send the genomic variant.
- Use the HCNC ID rather than the transcript ID, to prevent issues with certain transcripts and different versions.
- Disabled the link to MD for variants without any transcripts mapped to it.
- While determining which gene to send to MD, prioritize locations in the CDS rather than introns or UTRs, then measure the distance of the variant to any CDS and pick the lowest distance.
Closes #471.
> Improved the link to MobiDetails.

- src/class/object_custom_viewlists.php
- src/class/object_genome_variants.php
- src/class/object_transcript_variants.php
- src/class/object_transcripts.php
- src/transcripts.php
Small changes to the Variant ID fields:
- Resized the variant ID columns a bit, they could be made smaller.
- Resized the transcript ID columns a bit, they could be made smaller.
- All variant overviews now show the variant IDs, but only to Curators and up.
- Simple downloads could then more easily be used for imports, although modifications are always required to alert users of the dangers of update-imports.
> Small changes to the Variant ID fields

- src/class/object_genome_variants.php
- src/class/object_transcript_variants.php
- src/class/objects.php
- src/screenings.php
- src/variants.php
Fixed the variant ID field configuration.
- Fixed bug; The recent change unsetting the VOT `id_` field broke filtering on VOT ID for the VOG VE, breaking large databases.
- Standardizing the use of the `id` vs `id_` field. The `id` field will now always be present, and always be hidden, but usable for filtering.
- Added the definition of an `id` field for the VOG object that is always hidden and used for filtering.
- Removed the no longer necessary `cols_to_remove` setting for the VOG VLs in `screenings.php`.
- Standardized indentation for the VOG and VOT objects.
- Fixed bug; `formatArrayToTable()` was running `array_unique()` on an array with possibly nested arrays.
- This doesn't work as `array_unique()` by default converts everything to strings, after which a notice is thrown and it …
> Fixed the variant ID field configuration

- src/class/object_genome_variants.php
- src/inc-init.php
- src/inc-upgrade.php
- src/scripts/fetch_frequencies.php
Improved the imported frequencies.
- The variant field "Average frequency (large NGS studies)" used to be imported from a copy we obtained of the Exome Variant Server (EVS). Switching to GnomAD frequencies now, which we imported into [a separate LOVD instance](https://gnomad.lovd.nl/).
- Empty the `average_frequency` field, so we can update it with new data.
- Updated the URL from which the frequencies will be collected.
- Link directly to GnomAD to see the results, instead of our GnomAD LOVD instance.
> Improved the imported frequencies.

- src/class/variant_validator.php
- src/scripts/fix_variant_descriptions.php
Change 'Ter' amino acid to '*'.
- Variant Validator predictions will now contain `*` instead of `Ter`.
- This is what most publications and submitters use, and it's annoying to be searching for both to show nonsense variants.
- Standardize `*` over `Ter` in the variant validation script.
> Change 'Ter' amino acid to '*'.

- src/inc-lib-init.php
- src/inc-lib-variants.php
- tests/unit_tests/FixHGVS.php
Removed Conversion variant type.
- Updated `lovd_fixHGVS()`; No longer convert delins variants into con variants - con will be removed.
- See: http://varnomen.hgvs.org/bg-material/consultation/svd-wg009/
- Updated `lovd_fixHGVS()`; it will convert conversions into deletion-insertions.
- Updated test for `lovd_fixHGVS()`; conversions should be changed into deletion-insertions.
- Drop support for conversions in `lovd_getVariantInfo()` when `$bCheckHGVS` is true.
- Fixed some issues with `lovd_getVariantInfo()`.
- Extended matching of delins variants, allowing for positions.
- These positions actually require c. or g. when a reference sequence is included.
- Removed some verification of the "con" variant type, it's rejected for HGVS checks (but still supported for getting positions).
- …
> Removed Conversion variant type.

- src/class/object_shared_columns.php
- src/columns.php
- src/import.php
Fixed missing proper checks on select field values.
- Disallow semicolons to be used as selection options for fields created, edited, or imported.
- Disallow semicolons to be used as selection options for shared fields that are edited.
Closes #480.
> Fixed missing proper checks on select field values.

- src/genes.php
Automatically add the Entrez ID and OMIM ID to genes when editing them.
- When a gene has no Entrez ID or no OMIM ID but the HGNC does know these IDs now, LOVD will add them when the gene is edited.
- The gene must be created or last edited at least one week ago for LOVD to check for these IDs.
Closes #483.
> Automatically add the Entrez ID and OMIM ID to genes when editing them.

- src/class/object_transcript_variants.php
- src/inc-init.php
Fixed bug; VOT's `updateAll()` didn't handle numeric column like `updateEntry()` does, resulting in query errors for empty fields.
- These fields should have been caught and transformed into `NULL` values.
Also:
- Updated the upstream URL to prevent redirect issues.
- We require HTTPS now on the live site.
Closes #489.
> Fixed query error.

- src/class/api.submissions.php
Fixed bug; HGNC IDs weren't handled well in the submission API.
- `ctype_digit()` doesn't work always on integers.
- Closes #492.
> Fixed bug; HGNC IDs weren't handled well in the submission API.

- src/api.php
Replaced hard-coded table name with the proper constant that takes the configured table prefix into account.
- Part of the API didn't work anymore if the table prefix was not `lovd_v3`.
Closes #497.
> Fixed hard-coded table name

- src/inc-lib-init.php
Fixed bug in page titles when creating a new variant for a screening.
Closes #505.
> Fix bug in page titles when creating a new variant for a screening.

- src/reset_password.php
Fixed bugs in the password reset feature:
- The password reset code couldn't match accounts with multiple email addresses when the email address was used to reset the password.
- Improved reset password notification for accounts that don't exist.
- Fixed bug; unlocking an account using an email address didn't work.
Closes #507.
> Fix 507: Resetting password doesn't always work

- src/class/variant_validator.php
- src/genes.php
- src/inc-lib-genes.php
- src/transcripts.php
Fix problems with genes not supported by Mutalyzer by using VV as a backup.
- Prevent notices when Mutalyzer doesn't recognize a gene.
- VV: Get orientation from elsewhere in the structure. VV changed where a transcript's orientation is located in the JSON structure. See [openvar/variantValidator#253](https://github.com/openvar/variantValidator/issues/253#issuecomment-743188434).
- Started the migration by using VV as a backup for Mutalyzer when creating genes and adding transcripts to existing genes. There are too many "unsupported" genes right now, that have changed their symbol and therefore are no longer supported by Mutalyzer. VV can handle them just fine. For now, call VV only when Mutalyzer fails to generate a UD or when Mutalyzer fails to find transcripts at all.
Closes #513.
> Fix problems with genes not supported by Mutalyzer by using VV as a backup.

- src/inc-upgrade.php
Fix incorrect column size limit in the upgrade script.
It wasn't in sync with the installation script, and compound license settings actually didn't fit in the column.
> Fix incorrect column size limit in the upgrade script.

- src/inc-init.php
Patch an XSS vulnerability found by Chirag Mistry.
- He earlier also reported an XSS vulnerability in the LOVD website.
- Upon checking the LOVD software, he spotted this XSS too.
- Clean `$_SERVER['REQUEST_URI']` and overwrite so we can then safely use it everywhere.
- Restructure the URL parsing a bit.
> Fix XSS bug

- src/__function_list.txt
- src/ajax/licenses.php
- src/api.php
- src/class/api.ga4gh.php
- src/class/api.php
- src/class/object_custom.php
- src/class/object_genes.php
- src/class/object_genome_variants.php
- src/class/object_individuals.php
- src/class/object_phenotypes.php
- src/class/object_screenings.php
- src/class/template.php
Added the GA4GH Data Discovery API to LOVD3.
- This is a full LOVD3-specific implementation of the GA4GH Data Discovery standards without the use of other libraries.
- Supported URLs:
- `/api/v#/ga4gh` (GET/HEAD) (redirects)
- `/api/v#/ga4gh/service-info` (GET/HEAD)
- `/api/v#/ga4gh/tables` (GET/HEAD)
- `/api/v#/ga4gh/table/variants` (GET/HEAD) (redirects)
- `/api/v#/ga4gh/table/variants/info` (GET/HEAD)
- `/api/v#/ga4gh/table/variants/data` (GET/HEAD)
- `/api/v#/ga4gh/table/variants/data:hg19:chr1:123456` (GET/HEAD)
- `/api/v#/ga4gh/table/variants/data:hg19:chr1:123456-234567` (GET/HEAD)
- This endpoint is available from API version 2 (v2).
- This endpoint currently requires authorization.
- The data is shared using the VarioML [aggregated variant …
> Add the GA4GH Data Discovery API to LOVD3.

- src/ajax/viewentry.php
- src/class/object_diseases.php
- src/class/object_screenings.php
- src/class/object_transcript_variants.php
- src/class/objects.php
- src/screenings.php
Fix several query errors collected from the logs.
- Fix stupid typo that my test scripts should have picked up. If only my tests were working... still need to migrate to Travis.com.
- Fix notices with bad search syntax VLs.
- Fix query error in the query optimizer.
- Searching in the inheritance field using `HAVING` was confusing the query optimizer. It's a local column, so it should use `WHERE`.
- Fix SQL injection vulnerability.
- IDs sent through ajax weren't fully sanitized.
- Fix query error when not selecting variants to remove from a screening.
- Now, removing variants from a screening checks if you have selected at least one. This is the same as confirming variants to be added to a screening, so it's odd that this code differed.
Closes #527.
> Fix several query errors collected from the logs.

- src/class/objects.php
- src/inc-init.php
- src/reset_password.php
Improve security.
- Force some printed variables into integers.
- Although they're safe now (as long as the pagination is inited), we'd better force some variables into integers since they should be integers, before printing them to the screen.
- Also protect against other characters that can cause an XSS.
- None of these belong in our URLs.
- HTML entity encoded characters can also be used for XSS.
- Sleep for one second when resetting a password.
- This was reported as a possible dos vulnerability. Rate-limiting this client-side could easily be circumvented. I don't want to go through the trouble now and rate-limit this server-side (per IP address or so). Just a `sleep()` will be fine for now.
- Also synced the two different messages printed to the screen.
- Whether the password reset …
> Improve security.

- src/api.php
- src/class/api.ga4gh.php
- tests/selenium_tests/admin_tests/verify_GA4GH_API.php
- tests/selenium_tests/phpunit.xml
- tests/test_data_files/AdminTestSuiteResult-GA4GH.txt
Improve the GA4GH API.
- Remove imprinting comment for chrM variants.
- GV shared users often misuse this value.
- Let the LSDB ID just be and use something else for authorization.
- We now had `md5($_STAT['signature'])` already for quite some time as the LSDB ID, so no need to change it in the GA4GH API; it can already be read out through cookies, and anyway it only provides rights to use the submission API. Use something else for varcache to obtain rights in LOVD.
- Users calling the GA4GH API from localhost don't need authorization.
- Add skeleton file for the GA4GH API test.
- Test root of GA4GH API; it should redirect to `service-info`.
- Add test for the Service Info endpoint.
- Add test for the Tables endpoint.
- Add test for the Variants table URL, it should redirect to its data. …
> Improve the GA4GH API.

- src/class/object_custom.php
- src/class/object_users.php
- src/class/objects.php
Fix display of LOVD owned records. The owner field was displayed as empty for data owned by LOVD.
Also:
- Fix notice when stored license doesn't contain a semicolon.
Closes #533.
> Fix display of LOVD owned records

- src/ajax/licenses.php
- src/api.php
- src/class/object_genome_variants.php
- src/class/object_transcript_variants.php
- src/class/objects.php
- src/import.php
- src/individuals.php
- src/phenotypes.php
- src/screenings.php
- src/variants.php
Fixed various issues, preparing for release.
- Allow application/octet-stream as an import file.
- Some users are getting that file type (seems to depend on the browser), so allow it next to all `text/*` types.
- Remove spaces around select values when importing.
- When importing, providing a value for a multiple selection list like `PCR; SEQ` is valid, and ` SEQ` gets stored. This is because `checkFields()` trims the values, but the original values are left. The value then mismatches, giving some minor issues. When the entry is edited, the problem is also solved. But it's better to not import these spaces.
- This is now implemented into `checkFields()`, but the importer checks for differences before `checkFields()` is run, so entries with spaces in them will always trigger an update of …
> Fix various issues, preparing for release

- src/class/api.ga4gh.php
- tests/selenium_tests/admin_tests/multi_value_search.php
- tests/test_data_files/AdminTestSuiteResult-GA4GH.txt
Improved the GA4GH endpoint after the first uses in production.
- Add locations array to aggregated variants. These elements are new in VarioML.
- Fix GA4GH test after addition of location array.
- Remove empty panel array from aggregated variants.
- Since we're removing all keys in the panel object, PHP makes it an empty array when creating JSON, breaking the validation. Maybe removing these empty keys isn't such a great idea, because it also freaks out JQ.
- Work on 100 variants max, not 1000.
- Fix some issues with the calculation of the next position.
- When converting data for more than 15 seconds, return what you have.
Also:
- Don't let the MultiValueSearch test fail hard when not logged in.
> Improve the GA4GH endpoint

- src/api.php
- src/class/api.ga4gh.php
Several fixes to the APIs.
- The API couldn't search anymore since the recent SQL injection fix.
- `$_DB->quote()` adds quotes already, so we must remove ours.
- Fixed #548, showing random variant descriptions from alternative builds. Pick the first hg38 variant description output when listing unique variants. It now picked an entry at random, which could be an entry without an hg38 description.
- Remove a gene's MIM accession when it's empty.
Closes #548.
> Several fixes to the APIs.

- src/.htaccess
- src/class/object_genome_builds.php
- src/genome_builds.php
- src/inc-init.php
- src/inc-lib-init.php
- src/inc-upgrade.php
- Create the genome builds table when installing LOVD.
- Create the genome builds table when upgrading an existing LOVD instance.
- Create the genome builds VL.
- Create the genome builds VE.
- Version bump to 3.5-pre-01.
Related to #550.
> Have genome builds table created, and data viewable

- src/class/object_diseases.php
- src/class/object_genome_variants.php
- src/class/object_individuals.php
- src/class/object_phenotypes.php
- src/class/object_screenings.php
- src/class/object_system_settings.php
- src/class/object_transcript_variants.php
- src/class/object_transcripts.php
- src/class/object_users.php
- src/inc-lib-form.php
Fix lovd_checkXSS().
- Relaxed the new XSS check a bit.
- The less-than sign (`<`) wasn't allowed at all in fields anymore, but they are in use for age fields and probably other phenotype fields as well. So relaxed this check for all custom columns back to the previous XSS check. The newer check for no less-than at all, remains for non-custom columns.
- During import, make sure the XSS check is run on the import data.
- When `lovd_checkXSS()` is run without arguments, it runs on `$_POST` by default. During import, this is not the correct variable to run on. Make sure it runs on `$aData`, which resolves to either `$_POST` or, during import, to `$aLine`.
> Fix lovd_checkXSS().

- src/ajax/curate_set.php
- src/class/api.ga4gh.php
- src/class/api.submissions.php
- src/class/object_custom.php
- src/class/object_genome_variants.php
- src/class/object_transcript_variants.php
- src/class/objects.php
- src/class/template.php
- src/columns.php
- src/import.php
- src/inc-auth.php
- src/inc-lib-api.php
- src/inc-lib-form.php
- src/inc-lib-init.php
- src/inc-lib-variants.php
- src/inc-lib-viewlist.php
- src/scripts/convert_lovd2.php
- src/scripts/readingFrameChecker.php
- src/scripts/refseq_parser.php
- src/submit.php
- src/variants.php
LOVD is currently incompatible with PHP8 due to the removal of curly braces as a string access operator. The simple fix is to replace the curly braces with square brackets, but this may create confusion between strings and arrays (if it wasn't for our variable-naming). Using `$s[0]` rather than `substr($s, 0, 1)` is much faster, so whenever that wasn't losing readability, I used this. In the end, only in one place, I chose to use `substr()` to not create confusion between strings and arrays.
Replaced curly braces as string access operators in all files. Only skipped the `lovd_getVariantInfo()` function in `inc-lib-init.php`, as it's being rebuilt by @loeswerkman. Making changes there would just cause senseless merge conflicts.
Depends on #566.
Closes #571, but in reality only when …
> Fix LOVD for PHP8

- src/class/object_system_settings.php
- src/class/objects.php
- src/class/template.php
- src/columns.php
- src/genes.php
- src/inc-init.php
- src/inc-js-submit-settings.php
- src/phenotypes.php
- src/scripts/refseq_parser.php
- src/styles.css
- src/transcripts.php
- src/users.php
Fixed multiple issues:
- Remove some styling for optgroups, so users can see pre-selected items.
- Closes #570.
- Updated the copyright statement to 2022.
- Fix notice when not logged in, and remove unused code.
- Handle missing or deprecated `get_magic_quotes_gpc()`.
- Complete rebuild of the URL validation on the system settings form.
- We were notified of a blind SSRF in this feature (#577). We carefully reviewed the current functionality, and decided that some details about the review of the given URL could be left out. We'll otherwise NOT remove this feature, as it's important to validate an LOVD's URL. However, some improvements have been made.
- A sleep of half a second has been introduced in the upstream code. This makes abuse of the feature a bit harder.
- Any details of whether …
> Fixed multiple issues.

- src/genome_builds.php
From now on, when a new genome build is added, a new index will be built for the new position fields, and this index will be removed again when the build is removed.
Related to #550.
> Add/remove indices when adding/removing GBs

- src/class/variant_validator.php
- src/scripts/fix_variant_descriptions.php
Several fixes for the VariantValidator library.
- Small changes like delA to del were misinterpreted as a `WROLLFORWARD`.
- This was caused by a change on our side. The variant arrays were no longer the same due to changes in the warnings list.
- Treat `$aJSON['validation_warnings']` as a list, not one element.
- `$aData['warnings'][0]` became a list, and that doesn't make sense.
- Restructure the filtering of `$aJSON['validation_warnings']` a bit.
- This will allow us to take a better look at it and process more warnings to either hide them or pass them on.
- Catch `IREFSEQUPDATED` messages, alerting us about updated refseqs.
- This applies to VV only, not the LOVD endpoint.
- Also, reset keys of `$aJSON['validation_warnings']` since we're unsetting entries.
- Silently remove LRG-related …
> Fix VariantValidator library.

- src/api.php
- src/inc-init.php
- tests/upload_test_results.sh
Fix multiple issues.
- Complete fix from last year regarding `$_DB->quote()` in the API.
- This is related to https://github.com/LOVDnl/LOVD3/commit/83ad2c2ca9c2ade66d069f43004245a22e24e517.
- Unknown why I didn't pick up this remaining `quote()` method call that should get its quotes removed.
- Also, `$_GET` got changed into `GET`; fixed this as well.
- Fix `$_PE[1]` when it contains a gene symbol in the wrong case.
- The recent implementation of `lovd_getCurrentID()` and `lovd_getCurrentPageTitle()` has made LOVD sensitive again for incorrectly cased URLs.
> Fix multiple issues.

- src/ajax/check_HGVS.php
- src/class/variant_validator.php
- src/inc-lib-init.php
- src/inc-lib-variants.php
- tests/selenium_tests/shared_tests/check_HGVS_interface.php
- tests/unit_tests/FixHGVS.php
- tests/unit_tests/GetVariantInfoTest.php
Improved the HGVS functions:
- Clarify that we're just for DNA variants, in case we see `r.` or `p.`.
- Stop variants like `c.(101_102)G>A` to throw an `ESUFFIXMISSING`. Since `IPOSITIONRANGE` is active for those variants, our library requires a suffix to determine the length of the variant. However, substitutions always have a length of one, so no suffix is needed.
- Add a `WUNSUPPORTED` to variants like `c.(101_102)G>A`. VV doesn't support them, so we shouldn't send them.
- Let `lovd_fixHGVS()` deal with variants like `c.(100)del`.
- The variant recognition pattern is quite complex. An opening parenthesis is accepted without any problems, but a closing parenthesis after a position is only allowed when using ranges.
- The closing parenthesis in variants like `c.(100del)` just ends up in …
> Improved the HGVS functions and the VV library.

- src/ajax/map_variants.php
- src/class/PDO.php
- src/class/object_custom.php
- src/class/object_genes.php
- src/class/object_genome_variants.php
- src/class/object_individuals.php
- src/class/object_links.php
- src/class/object_transcripts.php
- src/class/objects.php
- src/class/template.php
- src/columns.php
- src/download.php
- src/genes.php
- src/import.php
- src/inc-js-viewlist.php
- src/inc-lib-form.php
- src/inc-lib-genes.php
- src/inc-lib-init.php
- src/individuals.php
- src/phenotypes.php
- src/screenings.php
- src/submit.php
- src/transcripts.php
- src/variants.php
- Remove a deprecation notice in `import.php`.
- Prevent warnings when running `ctype_digit()` on integers. Integers can't be run into `ctype_digit()` anymore; check using `is_int()` first, and then run `ctype_digit()`.
- Fix issues with functions no longer liking to receive null.
- Unbreak all JS row links on PHP 8.1. Row links were double-encoded. This was only noticed now that `htmlspecialchars()` also started to encode single quotes used in javascript row links. Undo this double encoding.
- Prevent some calculations on strings and integers. Strings are normally converted into integers, but an empty string isn't converted to 0. Other PHP versions would warn, but PHP 8.1 throws a fatal error. There may be more places where this happens.
- Apply standards in the spacing of control …
> Sync changes from LOVD+

- src/class/object_custom_viewlists.php
- src/class/object_genome_variants.php
- src/class/template.php
- src/inc-init.php
- src/inc-lib-init.php
- src/inc-upgrade.php
- src/install/inc-sql-links.php
- src/install/inc-sql-sources.php
- tests/selenium_tests/shared_tests/check_custom_links.php
- Create a new `$_SETT['external_sources']` and use it.
- Modified `lovd_getExternalSource()` to handle it.
- Replace hardcoded dbSNP links with `lovd_getExternalSource()`.
- Also replace all the custom links for dbSNP.
- Add reminder to the sources SQL file, deprecating it.
- Bump version to 3.0-28d.
Also:
- Update copyright in template.
> Fix dbSNP link.

- src/ajax/check_HGVS.php
- src/inc-lib-init.php
There were some fixes in the API; sync the code to LOVD3.
- Sync fix from api.lovd.nl. This caused NC:c variants to provide themselves as the fix for the problem, which makes no sense. This type of mistake requires human intervention.
- Add a fix to `lovd_cleanDirName()` that caused issues in the API. Constructing some URLs caused infinite recursion and crashed the PHP process due to maxing out the memory consumption.
> Sync code from the API

- src/ajax/check_HGVS.php
- src/class/variant_validator.php
Our VariantValidator library handles genomic variants and transcript variants differently; `verifyGenomic()` returns the variant with the reference sequence attached, while `verifyVariant()` removes the reference sequence.
- Keep the transcript in the `verifyVariant()` call. To simplify the output and keep it consistent with the mapping array returned by `verifyGenomic()`, the refseq is removed from the DNA field. But the `verifyVariant()` output had lost the transcript information completely; just by looking at the output, the input refseq could not be determined.
- Fix bug in checkHGVS ajax script related to `verifyVariant()`. Only `verifyVariant()` removes the transcript; `verifyGenomic()` does not.
Also:
- Fix bug; we might not have the given transcript in the database. This applies …
> VariantValidator: Reference sequences in `verifyVariant()`.

- src/class/api.ga4gh.php
- src/class/object_diseases.php
- src/class/object_genome_variants.php
- src/class/object_individuals.php
- src/class/object_phenotypes.php
- src/class/object_screenings.php
- src/class/object_transcripts.php
- tests/test_data_files/AdminTestSuiteResult-GA4GH.txt
- Set the `created_date` and `edited_date` fields to public access on ViewEntries. Only for genes, the `edited_date` is not made public to prevent confusion with the `updated_date` field. I can't remember why these fields are hidden, but many users would like to know how recent an entry is.
- Add dates to variant-only observations in the GA4GH API output.
- Add dates to full submissions in the GA4GH API output.
- Adapt the GA4GH test files after the updates.
Also:
- Clean phenotype output a bit in the GA4GH API output. I saw some empty phenotype objects; these are now skipped.
> Add dates to records

- src/class/api.ga4gh.php
- src/class/objects.php
- src/columns.php
- src/import.php
- src/inc-lib-form.php
- src/inc-lib-genes.php
- tests/test_data_files/AdminTestSuiteResult-GA4GH.txt
- Consider 0-dates as no dates.
- When there is no modification date, take the creation date.
- Also add dates to variants within full submissions.
- Fix tests.
- Improve `lovd_matchDate()` to enforce a valid date.
- Clarify error messages, mention valid dates are needed.
- Adjust `lovd_matchDate()` to optionally disallow 0-dates.
- Force non-zero dates for `created_date` and `edited_date` during import.
- Circumvent recurrent API issues with the HGNC that make the tests fail.
> More fixes to the date fields in the GA4GH API and in form data processing.

- src/class/api.submissions.php
- For variant-only submissions, refer to the Individual as `#0`. This ID is shown in errors and warnings, and Individual `#1` makes no sense when the file doesn't contain one.
- Disallow the `variant_detection` element for variant-only submissions.
- Check the `evidence_code` element, when present. Allowed values are 'classification_record', 'in_silico', 'in_vitro', and 'summary_record'.
- Disallow `evidence_code` with full submissions. VarioML allows this, but our values are meant for variant-only submissions, so we have to enforce using variant-only submissions.
- Disallow the `genetic_origin` element for variant-only submissions. Not only does the value make little sense for variant-only submissions, but we'll also need that field if we're to store evidence codes (summary records, …
> Improve the submission API

- src/ajax/map_variants.php
Prevent query errors in the mapper when a gene changed its symbol. We had 20K query errors in the logs. Fixed this now by checking first if the HGNC ID perhaps is in the database; if so, use that gene symbol.
> Prevent query errors in the mapper when a gene changed its symbol.

- src/api.php
- Fix quite old code in the LOVD2-style API that had a bug. Range matching on genes on the antisense strand didn't work.
- Improve code for partial variant position matching.
> Fix position matching in LOVD2-style API

- src/class/object_genes.php
- src/inc-init.php
- src/inc-upgrade.php
- src/install/inc-sql-sources.php
- Fix link to the Orphanet gene-specific pages.
- Orphanet no longer allows using HGNC IDs for linking. That's a bad thing, but there's no alternative.
- Version bump to 3.0-29b.
Closes #645.
> Links to Orphanet no longer work

- src/__function_list.txt
- src/ajax/licenses.php
- src/ajax/map_variants.php
- src/api.php
- src/class/api.ga4gh.php
- src/class/graphs.php
- src/class/object_genes.php
- src/inc-lib-init.php
- src/scripts/fetch_frequencies.php
- src/variants.php
- Fix issues with the mapper and variants with unknown positions. Variants with unknown positions get mapped to a large range internally. This causes issues with the variant mapper that is looking for overlapping transcripts with impossible positions.
- Also don't count these variants as variants that need mapping.
- Remove these variants also from the BED file export.
- Don't fetch frequencies for this type of variants.
- Handle NULL values for RNA and Protein fields in the GA4GH API.
- Remove all uses of "indel", it's a confusing term now. Nowadays, people often interpret it as a deletion or insertion, while we used it as "deletion-insertion". The HGVS nomenclature no longer uses the term for that reason.
- Add more DNA variant types to be recognized.
- Add the compound protein change …
> Fix multiple issues

- src/class/object_screenings.php
- src/individuals.php
- src/screenings.php
Already during development, a FIXME had been added to fix this, but this was overlooked. The gene-specific Screenings VL was not filtering well and was actually filtering very inefficiently. Today, LOVD's MySQL was overloaded by repeated requests for gene-specific Screenings VLs.
Fixed both issues by adding a virtual column that allows for efficient and effective filtering on the gene symbol instead of a `LIKE` on the compound gene list, which caused a hefty query time with a temp table and a file sort. This is the same solution that had already been applied to the gene-specific Individuals VL.
> Fix and optimize the gene-specific Screenings VL.

- src/ajax/mobidetails.php
- src/class/variant_validator.php
- Remove newlines in errors coming from Mobidetails. They break the JS, otherwise.
- Make sure we follow redirects. VV never used to redirect us, but now, it does. Reported it to VV, but also updated the code in case they keep it. See: https://github.com/openvar/variantValidator/issues/628.
- Support more error strings for `EREFSEQ`.
- Support more error strings for `IREFSEQUPDATED`.
> Update libraries/scripts connecting to external tools

- src/inc-lib-form.php
- src/inc-lib-init.php
- src/reset_password.php
- Fix a query error in the password reset feature, triggered when sending regex characters. This is not an SQL injection error as it doesn't let the user run malicious SQL, but it does break our query.
- Make sure the other `REGEXP` clauses are protected, too. These aren't known to cause any issues, and I haven't been able to trigger anything, but it's better to quote the input regardless to train myself to always quote whatever goes into a MySQL `REGEXP`.
Also:
- Fix an issue with the page title when creating a summary variant entry.
> Fix a query error related to a REGEXP

- doc/tex/manual.tex
- src/class/object_genes.php
This is an external rename of the resource; internally, the resource continues to be named "GeneTests". The reason for this is twofold: Firstly, renaming the internal fields is more work and requires a database migration, while LOVD users wouldn't know the difference. Secondly, this will change the format of the Gene data files, which may break other processes. As such, we're only updating the interface.
- Rename GeneTests to NIH Genetic Testing Registry (GTR) on the Gene homepage and the Gene data entry form. 
- Update relevant parts of the manual.
Also:
- Resolve an old FIXME while we're at it, located in the same code block we were already editing.
Closes #657.
> Rename GeneTests to NIH GTR

- doc/tex/manual.tex
- src/changelog.txt
- src/class/object_rate_limits.php
- src/class/template.php
- src/docs/index.php
- src/install/index.php
- src/scripts/refseq_parser.php
- Fix broken version check in the installer. LOVD wasn't installable on MySQL 10 due to LOVD thinking that '10.0.1' was smaller than '4.1.2'. Fixed this for both the PHP and MySQL version comparisons by exploding the version into parts.
- Remove broken links to old support material from the manual.
- Remove some more old stuff from the manual.
- Updated all links in the manual. Changed http to https where appropriate, and updated some URLs.
- Fix some other small issues in the manual source code.
- Update manual stats.
- Fix issues in the refseq parser:
- Fix `str_repeat()` called with a negative count.
- Fix `sum()` that included a string of spaces. I _assume_ that a `strlen()` of that string was meant, but the code is mega old and messy. The result looks OK for me, but I haven't tested …
> Fix various issues
